# Generated by Django 4.2.1 on 2023-08-26 06:32

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=240, null=True, verbose_name='Biografia')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='foto_de_perfil/', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('thumbnail', models.ImageField(upload_to='thumbnail_de_post', verbose_name='Miniatura da Postagem')),
                ('meta_description', models.CharField(blank=True, default=None, max_length=160, verbose_name='Meta Descrição')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publicar')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='get_slug', unique=True)),
                ('year', models.PositiveIntegerField(editable=False)),
                ('month', models.IntegerField(editable=False)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
