# Generated by Django 4.2.1 on 2023-09-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='main_01',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='main_02',
            field=models.BooleanField(default=False),
        ),
    ]
